networks:
  internal:
    driver: bridge

services:
  nginx:
    image: pagespeed/nginx-pagespeed:latest
    platform: linux/amd64
    ports:
      - '8090:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - pagespeed_cache:/var/cache/ngx_pagespeed
    restart: unless-stopped
    networks:
      - default
    logging:
      driver: json-file
      options:
        tag: "{{.Name}}"

  php-fpm:
    image: php:8.1-fpm
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      - default
    logging:
      driver: json-file
      options:
        tag: "{{.Name}}"

volumes:
  pagespeed_cache:
